[project]
name = "knmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-openai>=0.3.14",
    "mcp-use>=1.2.8",
    "mcp[cli]>=1.6.0",
]
